<?php

namespace App\Http\Controllers;

use Faker\Factory;
use Illuminate\Http\Request;

class MarkdownController extends Controller
{
    public function __invoke(Request $request)
    {
        $sections = min(max((int) $request->query('sections', 5), 1), 20);
        $title = substr($request->query('title', ''), 0, 200);
        $seed = $request->query('seed');
        $features = $request->query('features', 'all');

        $faker = Factory::create();
        if ($seed !== null) {
            $faker->seed((int) $seed);
        }

        $enabledFeatures = $this->parseFeatures($features);

        if (empty($title)) {
            $title = ucfirst($faker->words(rand(4, 8), true));
        }

        $md = "# {$title}\n\n";
        $md .= "> " . $faker->sentence(rand(10, 20)) . "\n\n";

        if (in_array('toc', $enabledFeatures)) {
            $md .= "## Table of Contents\n\n";
            for ($i = 1; $i <= $sections; $i++) {
                $md .= "- [Section {$i}](#section-{$i})\n";
            }
            $md .= "\n---\n\n";
        }

        for ($i = 1; $i <= $sections; $i++) {
            $md .= "## " . ucfirst($faker->words(rand(3, 7), true)) . "\n\n";

            $md .= $faker->paragraph(rand(3, 6)) . "\n\n";

            $elements = $this->pickElements($faker, $enabledFeatures);

            foreach ($elements as $element) {
                $md .= match ($element) {
                    'paragraph' => $faker->paragraph(rand(2, 5)) . "\n\n",
                    'list' => $this->generateList($faker),
                    'ordered_list' => $this->generateOrderedList($faker),
                    'code' => $this->generateCodeBlock($faker),
                    'table' => $this->generateTable($faker),
                    'blockquote' => "> " . $faker->sentence(rand(8, 20)) . "\n\n",
                    'image' => "![" . $faker->words(3, true) . "](https://placehold.cloud/600x300?text=" . urlencode($faker->words(2, true)) . ")\n\n",
                    'link' => "[" . ucfirst($faker->words(rand(2, 4), true)) . "](" . $faker->url() . ")\n\n",
                    'bold_italic' => $this->generateFormattedParagraph($faker),
                    'h3' => "### " . ucfirst($faker->words(rand(3, 6), true)) . "\n\n" . $faker->paragraph(rand(2, 4)) . "\n\n",
                    default => '',
                };
            }
        }

        $md .= "---\n\n*Generated by [placehold.cloud](https://placehold.cloud) on " . now()->toDateString() . "*\n";

        return response($md)
            ->header('Content-Type', 'text/markdown; charset=UTF-8')
            ->header('Content-Disposition', 'inline; filename="document.md"')
            ->header('Cache-Control', $seed !== null ? 'public, max-age=3600' : 'no-cache, no-store, must-revalidate');
    }

    private function parseFeatures(string $features): array
    {
        $all = ['paragraph', 'list', 'ordered_list', 'code', 'table', 'blockquote', 'image', 'link', 'bold_italic', 'h3', 'toc'];

        if ($features === 'all') {
            return $all;
        }

        return array_filter(
            array_map('trim', explode(',', $features)),
            fn($f) => in_array($f, $all)
        );
    }

    private function pickElements(\Faker\Generator $faker, array $enabled): array
    {
        $pool = array_diff($enabled, ['toc']);
        if (empty($pool)) {
            $pool = ['paragraph'];
        }

        $count = rand(2, 4);
        $elements = [];
        $poolValues = array_values($pool);

        for ($i = 0; $i < $count; $i++) {
            $elements[] = $faker->randomElement($poolValues);
        }

        return $elements;
    }

    private function generateList(\Faker\Generator $faker): string
    {
        $items = rand(3, 7);
        $md = '';
        for ($i = 0; $i < $items; $i++) {
            $md .= "- " . $faker->sentence(rand(4, 10)) . "\n";
            if (rand(0, 3) === 0) {
                $md .= "  - " . $faker->sentence(rand(3, 6)) . "\n";
            }
        }
        return $md . "\n";
    }

    private function generateOrderedList(\Faker\Generator $faker): string
    {
        $items = rand(3, 6);
        $md = '';
        for ($i = 1; $i <= $items; $i++) {
            $md .= "{$i}. " . $faker->sentence(rand(4, 10)) . "\n";
        }
        return $md . "\n";
    }

    private function generateCodeBlock(\Faker\Generator $faker): string
    {
        $lang = $faker->randomElement(['javascript', 'python', 'php', 'bash', 'json', 'html', 'css']);

        $snippets = [
            'javascript' => "function " . $faker->word() . "(data) {\n  const result = data.map(item => item.value);\n  console.log('Processing:', result.length, 'items');\n  return result.filter(Boolean);\n}",
            'python' => "def " . $faker->word() . "(items):\n    \"\"\"Process the given items.\"\"\"\n    result = [x for x in items if x.is_valid]\n    print(f'Found {len(result)} valid items')\n    return result",
            'php' => "\$" . $faker->word() . " = collect(\$items)\n    ->filter(fn (\$item) => \$item->isActive())\n    ->map(fn (\$item) => \$item->transform())\n    ->values();",
            'bash' => "#!/bin/bash\nfor file in *.txt; do\n  echo \"Processing \$file\"\n  wc -l \"\$file\"\ndone",
            'json' => "{\n  \"name\": \"" . $faker->word() . "\",\n  \"version\": \"1.0.0\",\n  \"dependencies\": {\n    \"lodash\": \"^4.17.0\"\n  }\n}",
            'html' => "<div class=\"container\">\n  <h1>" . $faker->words(3, true) . "</h1>\n  <p>" . $faker->sentence() . "</p>\n</div>",
            'css' => ".container {\n  display: flex;\n  gap: 1rem;\n  padding: 2rem;\n  background: #f8f9fa;\n  border-radius: 8px;\n}",
        ];

        return "```{$lang}\n" . $snippets[$lang] . "\n```\n\n";
    }

    private function generateTable(\Faker\Generator $faker): string
    {
        $cols = rand(3, 5);
        $rows = rand(3, 6);

        $headers = [];
        for ($c = 0; $c < $cols; $c++) {
            $headers[] = ucfirst($faker->word());
        }

        $md = "| " . implode(' | ', $headers) . " |\n";
        $md .= "| " . implode(' | ', array_fill(0, $cols, '---')) . " |\n";

        for ($r = 0; $r < $rows; $r++) {
            $cells = [];
            for ($c = 0; $c < $cols; $c++) {
                $cells[] = $faker->words(rand(1, 3), true);
            }
            $md .= "| " . implode(' | ', $cells) . " |\n";
        }

        return $md . "\n";
    }

    private function generateFormattedParagraph(\Faker\Generator $faker): string
    {
        $sentences = [];
        for ($i = 0; $i < rand(3, 6); $i++) {
            $s = $faker->sentence(rand(6, 14));
            $r = rand(0, 3);
            $s = match ($r) {
                0 => "**" . $s . "**",
                1 => "*" . $s . "*",
                2 => "`" . $faker->word() . "` " . $s,
                default => $s,
            };
            $sentences[] = $s;
        }
        return implode(' ', $sentences) . "\n\n";
    }
}
