<?php

namespace App\Http\Controllers;

use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Http\Request;

class PdfController extends Controller
{
    public function __invoke(Request $request)
    {
        $pages = min(max((int) $request->query('pages', 3), 1), 50);
        $title = substr($request->query('title', 'Sample Document'), 0, 200);
        $pageSize = in_array($request->query('size', 'a4'), ['a4', 'letter', 'legal']) ? $request->query('size', 'a4') : 'a4';
        $orientation = $request->query('orientation', 'portrait') === 'landscape' ? 'landscape' : 'portrait';

        $faker = \Faker\Factory::create();
        $content = [];

        for ($i = 1; $i <= $pages; $i++) {
            $sections = [];
            $sectionCount = rand(2, 4);
            for ($s = 0; $s < $sectionCount; $s++) {
                $sections[] = [
                    'heading' => $faker->sentence(rand(3, 8)),
                    'paragraphs' => $faker->paragraphs(rand(2, 5)),
                ];
            }
            $content[] = $sections;
        }

        $html = $this->buildHtml($title, $content);

        $pdf = Pdf::loadHTML($html)->setPaper($pageSize, $orientation);

        $filename = str_replace(' ', '-', strtolower($title)) . '.pdf';

        return $pdf->stream($filename)
            ->header('Cache-Control', 'public, max-age=3600');
    }

    private function buildHtml(string $title, array $content): string
    {
        $pages = '';
        foreach ($content as $i => $sections) {
            $isFirst = $i === 0;
            $pageBreak = $isFirst ? '' : 'page-break-before: always;';

            $body = '';
            foreach ($sections as $section) {
                $paragraphs = implode('', array_map(fn($p) => "<p style=\"margin-bottom:10px;line-height:1.6;color:#374151;\">$p</p>", $section['paragraphs']));
                $body .= "<h2 style=\"font-size:16px;font-weight:600;color:#1f2937;margin:20px 0 10px;\">{$section['heading']}</h2>" . $paragraphs;
            }

            $header = $isFirst
                ? "<h1 style=\"font-size:26px;font-weight:700;color:#111827;margin-bottom:8px;\">$title</h1><p style=\"color:#6b7280;margin-bottom:24px;font-size:13px;\">Generated by placehold.cloud</p><hr style=\"border:none;border-top:1px solid #e5e7eb;margin-bottom:24px;\">"
                : '';

            $pageNum = $i + 1;
            $totalPages = count($content);

            $pages .= "<div style=\"{$pageBreak}\">{$header}{$body}<div style=\"text-align:center;color:#9ca3af;font-size:11px;margin-top:30px;\">Page {$pageNum} of {$totalPages}</div></div>";
        }

        return "<!DOCTYPE html><html><head><meta charset=\"UTF-8\"><style>body{font-family:DejaVu Sans,sans-serif;font-size:13px;margin:40px;color:#374151;}</style></head><body>{$pages}</body></html>";
    }
}
