<?php

namespace App\Jobs;

use Barryvdh\DomPDF\Facade\Pdf;
use Faker\Factory as FakerFactory;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Str;

class GeneratePdfJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public int $timeout = 60;

    public function __construct(
        public int $pages,
        public string $title,
        public string $pageSize,
        public string $orientation,
        public string $callbackUrl,
        public ?string $jobId = null,
    ) {}

    public function handle(): void
    {
        $jobId = $this->jobId ?? (string) Str::uuid();
        $uuid = (string) Str::uuid();
        $dir = storage_path('app/generated');
        if (! is_dir($dir)) {
            mkdir($dir, 0755, true);
        }
        $outputPath = $dir . '/' . $uuid . '.pdf';

        $faker = FakerFactory::create();
        $content = [];

        for ($i = 1; $i <= $this->pages; $i++) {
            $sections = [];
            $sectionCount = rand(2, 4);
            for ($s = 0; $s < $sectionCount; $s++) {
                $sections[] = [
                    'heading' => $faker->sentence(rand(3, 8)),
                    'paragraphs' => $faker->paragraphs(rand(2, 5)),
                ];
            }
            $content[] = $sections;
        }

        $html = $this->buildHtml($this->title, $content);
        Pdf::loadHTML($html)->setPaper($this->pageSize, $this->orientation)->save($outputPath);

        if (! file_exists($outputPath)) {
            $this->notifyCallback($jobId, 'failed', null, 'PDF generation failed.');
            return;
        }

        $url = url('/generated/pdf/' . $uuid);
        $this->notifyCallback($jobId, 'completed', $url, null);
    }

    private function notifyCallback(string $jobId, string $status, ?string $url, ?string $message): void
    {
        $payload = [
            'job_id' => $jobId,
            'status' => $status,
            'expires_in' => 3600,
        ];
        if ($url) {
            $payload['url'] = $url;
        }
        if ($message) {
            $payload['message'] = $message;
        }

        try {
            Http::timeout(10)->post($this->callbackUrl, $payload);
        } catch (\Throwable) {
            //
        }
    }

    private function buildHtml(string $title, array $content): string
    {
        $pages = '';
        foreach ($content as $i => $sections) {
            $isFirst = $i === 0;
            $pageBreak = $isFirst ? '' : 'page-break-before: always;';

            $body = '';
            foreach ($sections as $section) {
                $paragraphs = implode('', array_map(fn ($p) => "<p style=\"margin-bottom:10px;line-height:1.6;color:#374151;\">$p</p>", $section['paragraphs']));
                $body .= "<h2 style=\"font-size:16px;font-weight:600;color:#1f2937;margin:20px 0 10px;\">{$section['heading']}</h2>" . $paragraphs;
            }

            $header = $isFirst
                ? "<h1 style=\"font-size:26px;font-weight:700;color:#111827;margin-bottom:8px;\">$title</h1><p style=\"color:#6b7280;margin-bottom:24px;font-size:13px;\">Generated by placehold.cloud</p><hr style=\"border:none;border-top:1px solid #e5e7eb;margin-bottom:24px;\">"
                : '';

            $pageNum = $i + 1;
            $totalPages = count($content);

            $pages .= "<div style=\"{$pageBreak}\">{$header}{$body}<div style=\"text-align:center;color:#9ca3af;font-size:11px;margin-top:30px;\">Page {$pageNum} of {$totalPages}</div></div>";
        }

        return "<!DOCTYPE html><html><head><meta charset=\"UTF-8\"><style>body{font-family:DejaVu Sans,sans-serif;font-size:13px;margin:40px;color:#374151;}</style></head><body>{$pages}</body></html>";
    }
}
